#ifndef ENUMS_H
#define ENUMS_H

enum SELECTOR {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, MOUSE};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum ACTION{NONE, CLEAR, INCREASE, DECREASE, BRINGFRONT, SENDBACK};



#endif